services:
  - type: web
    name: quick-order-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 3001
